#ifndef CONFIG_H
#define CONFIG_H

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define STATIC_IP 192,168,1,100
#define GATEWAY_IP 192,168,1,1

#define TELEGRAM_BOT_TOKEN "YOUR_TELEGRAM_BOT_TOKEN"
#define TELEGRAM_CHAT_ID_VALUE "YOUR_TELEGRAM_CHAT_ID"

#define OTA_PASSWORD "YOUR_OTA_PASSWORD"

#define DEVICE_MAC "YOUR_DEVICE_MAC"

#define LATITUDE_VAL 55.7558f
#define LONGITUDE_VAL 37.6173f

#endif
